// Generated by gencpp from file my_services/ObjectPositionService.msg
// DO NOT EDIT!


#ifndef MY_SERVICES_MESSAGE_OBJECTPOSITIONSERVICE_H
#define MY_SERVICES_MESSAGE_OBJECTPOSITIONSERVICE_H

#include <ros/service_traits.h>


#include <my_services/ObjectPositionServiceRequest.h>
#include <my_services/ObjectPositionServiceResponse.h>


namespace my_services
{

struct ObjectPositionService
{

typedef ObjectPositionServiceRequest Request;
typedef ObjectPositionServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObjectPositionService
} // namespace my_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_services::ObjectPositionService > {
  static const char* value()
  {
    return "6d1b74b2e09de95ba7cb8ac42e760730";
  }

  static const char* value(const ::my_services::ObjectPositionService&) { return value(); }
};

template<>
struct DataType< ::my_services::ObjectPositionService > {
  static const char* value()
  {
    return "my_services/ObjectPositionService";
  }

  static const char* value(const ::my_services::ObjectPositionService&) { return value(); }
};


// service_traits::MD5Sum< ::my_services::ObjectPositionServiceRequest> should match
// service_traits::MD5Sum< ::my_services::ObjectPositionService >
template<>
struct MD5Sum< ::my_services::ObjectPositionServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_services::ObjectPositionService >::value();
  }
  static const char* value(const ::my_services::ObjectPositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_services::ObjectPositionServiceRequest> should match
// service_traits::DataType< ::my_services::ObjectPositionService >
template<>
struct DataType< ::my_services::ObjectPositionServiceRequest>
{
  static const char* value()
  {
    return DataType< ::my_services::ObjectPositionService >::value();
  }
  static const char* value(const ::my_services::ObjectPositionServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_services::ObjectPositionServiceResponse> should match
// service_traits::MD5Sum< ::my_services::ObjectPositionService >
template<>
struct MD5Sum< ::my_services::ObjectPositionServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_services::ObjectPositionService >::value();
  }
  static const char* value(const ::my_services::ObjectPositionServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_services::ObjectPositionServiceResponse> should match
// service_traits::DataType< ::my_services::ObjectPositionService >
template<>
struct DataType< ::my_services::ObjectPositionServiceResponse>
{
  static const char* value()
  {
    return DataType< ::my_services::ObjectPositionService >::value();
  }
  static const char* value(const ::my_services::ObjectPositionServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVICES_MESSAGE_OBJECTPOSITIONSERVICE_H
