// Generated by gencpp from file my_services/PickPlace2Goal.msg
// DO NOT EDIT!


#ifndef MY_SERVICES_MESSAGE_PICKPLACE2GOAL_H
#define MY_SERVICES_MESSAGE_PICKPLACE2GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace my_services
{
template <class ContainerAllocator>
struct PickPlace2Goal_
{
  typedef PickPlace2Goal_<ContainerAllocator> Type;

  PickPlace2Goal_()
    : id(0)
    , pose()
    , location()  {
    }
  PickPlace2Goal_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::my_services::PickPlace2Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_services::PickPlace2Goal_<ContainerAllocator> const> ConstPtr;

}; // struct PickPlace2Goal_

typedef ::my_services::PickPlace2Goal_<std::allocator<void> > PickPlace2Goal;

typedef boost::shared_ptr< ::my_services::PickPlace2Goal > PickPlace2GoalPtr;
typedef boost::shared_ptr< ::my_services::PickPlace2Goal const> PickPlace2GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_services::PickPlace2Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_services::PickPlace2Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_services::PickPlace2Goal_<ContainerAllocator1> & lhs, const ::my_services::PickPlace2Goal_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose &&
    lhs.location == rhs.location;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_services::PickPlace2Goal_<ContainerAllocator1> & lhs, const ::my_services::PickPlace2Goal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_services::PickPlace2Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_services::PickPlace2Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PickPlace2Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PickPlace2Goal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PickPlace2Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PickPlace2Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_services::PickPlace2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "294d86574595b4f78b89451d18b8a490";
  }

  static const char* value(const ::my_services::PickPlace2Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x294d86574595b4f7ULL;
  static const uint64_t static_value2 = 0x8b89451d18b8a490ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_services::PickPlace2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_services/PickPlace2Goal";
  }

  static const char* value(const ::my_services::PickPlace2Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_services::PickPlace2Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"uint8 id\n"
"geometry_msgs/Pose pose\n"
"string location\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_services::PickPlace2Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_services::PickPlace2Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickPlace2Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_services::PickPlace2Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_services::PickPlace2Goal_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICES_MESSAGE_PICKPLACE2GOAL_H
