// Generated by gencpp from file my_services/PickPlaceGoal.msg
// DO NOT EDIT!


#ifndef MY_SERVICES_MESSAGE_PICKPLACEGOAL_H
#define MY_SERVICES_MESSAGE_PICKPLACEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace my_services
{
template <class ContainerAllocator>
struct PickPlaceGoal_
{
  typedef PickPlaceGoal_<ContainerAllocator> Type;

  PickPlaceGoal_()
    : id(0)
    , pose()  {
    }
  PickPlaceGoal_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::my_services::PickPlaceGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_services::PickPlaceGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PickPlaceGoal_

typedef ::my_services::PickPlaceGoal_<std::allocator<void> > PickPlaceGoal;

typedef boost::shared_ptr< ::my_services::PickPlaceGoal > PickPlaceGoalPtr;
typedef boost::shared_ptr< ::my_services::PickPlaceGoal const> PickPlaceGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_services::PickPlaceGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_services::PickPlaceGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_services::PickPlaceGoal_<ContainerAllocator1> & lhs, const ::my_services::PickPlaceGoal_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_services::PickPlaceGoal_<ContainerAllocator1> & lhs, const ::my_services::PickPlaceGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_services::PickPlaceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_services::PickPlaceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PickPlaceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PickPlaceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PickPlaceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PickPlaceGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_services::PickPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "496d91d6f8c51d776c1feee502f9e9ff";
  }

  static const char* value(const ::my_services::PickPlaceGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x496d91d6f8c51d77ULL;
  static const uint64_t static_value2 = 0x6c1feee502f9e9ffULL;
};

template<class ContainerAllocator>
struct DataType< ::my_services::PickPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_services/PickPlaceGoal";
  }

  static const char* value(const ::my_services::PickPlaceGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_services::PickPlaceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"uint8 id\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_services::PickPlaceGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_services::PickPlaceGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickPlaceGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_services::PickPlaceGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_services::PickPlaceGoal_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICES_MESSAGE_PICKPLACEGOAL_H
