// Generated by gencpp from file my_services/PoseFinderService.msg
// DO NOT EDIT!


#ifndef MY_SERVICES_MESSAGE_POSEFINDERSERVICE_H
#define MY_SERVICES_MESSAGE_POSEFINDERSERVICE_H

#include <ros/service_traits.h>


#include <my_services/PoseFinderServiceRequest.h>
#include <my_services/PoseFinderServiceResponse.h>


namespace my_services
{

struct PoseFinderService
{

typedef PoseFinderServiceRequest Request;
typedef PoseFinderServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseFinderService
} // namespace my_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_services::PoseFinderService > {
  static const char* value()
  {
    return "db8bd25f1ebf7eaf192d38a6e222e58e";
  }

  static const char* value(const ::my_services::PoseFinderService&) { return value(); }
};

template<>
struct DataType< ::my_services::PoseFinderService > {
  static const char* value()
  {
    return "my_services/PoseFinderService";
  }

  static const char* value(const ::my_services::PoseFinderService&) { return value(); }
};


// service_traits::MD5Sum< ::my_services::PoseFinderServiceRequest> should match
// service_traits::MD5Sum< ::my_services::PoseFinderService >
template<>
struct MD5Sum< ::my_services::PoseFinderServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_services::PoseFinderService >::value();
  }
  static const char* value(const ::my_services::PoseFinderServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_services::PoseFinderServiceRequest> should match
// service_traits::DataType< ::my_services::PoseFinderService >
template<>
struct DataType< ::my_services::PoseFinderServiceRequest>
{
  static const char* value()
  {
    return DataType< ::my_services::PoseFinderService >::value();
  }
  static const char* value(const ::my_services::PoseFinderServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_services::PoseFinderServiceResponse> should match
// service_traits::MD5Sum< ::my_services::PoseFinderService >
template<>
struct MD5Sum< ::my_services::PoseFinderServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_services::PoseFinderService >::value();
  }
  static const char* value(const ::my_services::PoseFinderServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_services::PoseFinderServiceResponse> should match
// service_traits::DataType< ::my_services::PoseFinderService >
template<>
struct DataType< ::my_services::PoseFinderServiceResponse>
{
  static const char* value()
  {
    return DataType< ::my_services::PoseFinderService >::value();
  }
  static const char* value(const ::my_services::PoseFinderServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVICES_MESSAGE_POSEFINDERSERVICE_H
