// Generated by gencpp from file my_services/PoseFinderServiceResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICES_MESSAGE_POSEFINDERSERVICERESPONSE_H
#define MY_SERVICES_MESSAGE_POSEFINDERSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace my_services
{
template <class ContainerAllocator>
struct PoseFinderServiceResponse_
{
  typedef PoseFinderServiceResponse_<ContainerAllocator> Type;

  PoseFinderServiceResponse_()
    : place_pose()  {
    }
  PoseFinderServiceResponse_(const ContainerAllocator& _alloc)
    : place_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _place_pose_type;
  _place_pose_type place_pose;





  typedef boost::shared_ptr< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseFinderServiceResponse_

typedef ::my_services::PoseFinderServiceResponse_<std::allocator<void> > PoseFinderServiceResponse;

typedef boost::shared_ptr< ::my_services::PoseFinderServiceResponse > PoseFinderServiceResponsePtr;
typedef boost::shared_ptr< ::my_services::PoseFinderServiceResponse const> PoseFinderServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_services::PoseFinderServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_services::PoseFinderServiceResponse_<ContainerAllocator1> & lhs, const ::my_services::PoseFinderServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.place_pose == rhs.place_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_services::PoseFinderServiceResponse_<ContainerAllocator1> & lhs, const ::my_services::PoseFinderServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2361449dcd5b5b1d495ad63a009503a2";
  }

  static const char* value(const ::my_services::PoseFinderServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2361449dcd5b5b1dULL;
  static const uint64_t static_value2 = 0x495ad63a009503a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_services/PoseFinderServiceResponse";
  }

  static const char* value(const ::my_services::PoseFinderServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose place_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_services::PoseFinderServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.place_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseFinderServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_services::PoseFinderServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_services::PoseFinderServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "place_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.place_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICES_MESSAGE_POSEFINDERSERVICERESPONSE_H
