(cl:defpackage my_services-srv
  (:use )
  (:export
   "OBJECTPOSITIONSERVICE"
   "<OBJECTPOSITIONSERVICE-REQUEST>"
   "OBJECTPOSITIONSERVICE-REQUEST"
   "<OBJECTPOSITIONSERVICE-RESPONSE>"
   "OBJECTPOSITIONSERVICE-RESPONSE"
   "POSEFINDERSERVICE"
   "<POSEFINDERSERVICE-REQUEST>"
   "POSEFINDERSERVICE-REQUEST"
   "<POSEFINDERSERVICE-RESPONSE>"
   "POSEFINDERSERVICE-RESPONSE"
  ))

