// Generated by gencpp from file goal_state_publisher/MoveGripperMsg.msg
// DO NOT EDIT!


#ifndef GOAL_STATE_PUBLISHER_MESSAGE_MOVEGRIPPERMSG_H
#define GOAL_STATE_PUBLISHER_MESSAGE_MOVEGRIPPERMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace goal_state_publisher
{
template <class ContainerAllocator>
struct MoveGripperMsg_
{
  typedef MoveGripperMsg_<ContainerAllocator> Type;

  MoveGripperMsg_()
    : width(0.0)
    , speed(0.0)  {
    }
  MoveGripperMsg_(const ContainerAllocator& _alloc)
    : width(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef double _width_type;
  _width_type width;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGripperMsg_

typedef ::goal_state_publisher::MoveGripperMsg_<std::allocator<void> > MoveGripperMsg;

typedef boost::shared_ptr< ::goal_state_publisher::MoveGripperMsg > MoveGripperMsgPtr;
typedef boost::shared_ptr< ::goal_state_publisher::MoveGripperMsg const> MoveGripperMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator1> & lhs, const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator1> & lhs, const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace goal_state_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d16050a0fe85f1c2cb8347c99678362e";
  }

  static const char* value(const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd16050a0fe85f1c2ULL;
  static const uint64_t static_value2 = 0xcb8347c99678362eULL;
};

template<class ContainerAllocator>
struct DataType< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "goal_state_publisher/MoveGripperMsg";
  }

  static const char* value(const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A custom message type for sending commands to a Franka gripper\n"
"# Define the message fields\n"
"float64 width\n"
"float64 speed\n"
"\n"
;
  }

  static const char* value(const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGripperMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::goal_state_publisher::MoveGripperMsg_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOAL_STATE_PUBLISHER_MESSAGE_MOVEGRIPPERMSG_H
