// Generated by gencpp from file goal_state_publisher/StopGripperMsg.msg
// DO NOT EDIT!


#ifndef GOAL_STATE_PUBLISHER_MESSAGE_STOPGRIPPERMSG_H
#define GOAL_STATE_PUBLISHER_MESSAGE_STOPGRIPPERMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace goal_state_publisher
{
template <class ContainerAllocator>
struct StopGripperMsg_
{
  typedef StopGripperMsg_<ContainerAllocator> Type;

  StopGripperMsg_()
    : isStop(false)  {
    }
  StopGripperMsg_(const ContainerAllocator& _alloc)
    : isStop(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isStop_type;
  _isStop_type isStop;





  typedef boost::shared_ptr< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> const> ConstPtr;

}; // struct StopGripperMsg_

typedef ::goal_state_publisher::StopGripperMsg_<std::allocator<void> > StopGripperMsg;

typedef boost::shared_ptr< ::goal_state_publisher::StopGripperMsg > StopGripperMsgPtr;
typedef boost::shared_ptr< ::goal_state_publisher::StopGripperMsg const> StopGripperMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator1> & lhs, const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator2> & rhs)
{
  return lhs.isStop == rhs.isStop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator1> & lhs, const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace goal_state_publisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e622c3bf7f741ad63c7902f5596d407";
  }

  static const char* value(const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e622c3bf7f741adULL;
  static const uint64_t static_value2 = 0x63c7902f5596d407ULL;
};

template<class ContainerAllocator>
struct DataType< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "goal_state_publisher/StopGripperMsg";
  }

  static const char* value(const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A custom message type for sending commands to a Franka gripper\n"
"# Define the message fields\n"
"bool isStop\n"
;
  }

  static const char* value(const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isStop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopGripperMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::goal_state_publisher::StopGripperMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::goal_state_publisher::StopGripperMsg_<ContainerAllocator>& v)
  {
    s << indent << "isStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOAL_STATE_PUBLISHER_MESSAGE_STOPGRIPPERMSG_H
