; Auto-generated. Do not edit!


(cl:in-package my_services-msg)


;//! \htmlinclude PickPlace2Result.msg.html

(cl:defclass <PickPlace2Result> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PickPlace2Result (<PickPlace2Result>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickPlace2Result>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickPlace2Result)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_services-msg:<PickPlace2Result> is deprecated: use my_services-msg:PickPlace2Result instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PickPlace2Result>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_services-msg:success-val is deprecated.  Use my_services-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickPlace2Result>) ostream)
  "Serializes a message object of type '<PickPlace2Result>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickPlace2Result>) istream)
  "Deserializes a message object of type '<PickPlace2Result>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickPlace2Result>)))
  "Returns string type for a message object of type '<PickPlace2Result>"
  "my_services/PickPlace2Result")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickPlace2Result)))
  "Returns string type for a message object of type 'PickPlace2Result"
  "my_services/PickPlace2Result")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickPlace2Result>)))
  "Returns md5sum for a message object of type '<PickPlace2Result>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickPlace2Result)))
  "Returns md5sum for a message object of type 'PickPlace2Result"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickPlace2Result>)))
  "Returns full string definition for message of type '<PickPlace2Result>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickPlace2Result)))
  "Returns full string definition for message of type 'PickPlace2Result"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickPlace2Result>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickPlace2Result>))
  "Converts a ROS message object to a list"
  (cl:list 'PickPlace2Result
    (cl:cons ':success (success msg))
))
