; Auto-generated. Do not edit!


(cl:in-package my_services-msg)


;//! \htmlinclude PickPlaceFeedback.msg.html

(cl:defclass <PickPlaceFeedback> (roslisp-msg-protocol:ros-message)
  ((info
    :reader info
    :initarg :info
    :type cl:string
    :initform ""))
)

(cl:defclass PickPlaceFeedback (<PickPlaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickPlaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickPlaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_services-msg:<PickPlaceFeedback> is deprecated: use my_services-msg:PickPlaceFeedback instead.")))

(cl:ensure-generic-function 'info-val :lambda-list '(m))
(cl:defmethod info-val ((m <PickPlaceFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_services-msg:info-val is deprecated.  Use my_services-msg:info instead.")
  (info m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickPlaceFeedback>) ostream)
  "Serializes a message object of type '<PickPlaceFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'info))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'info))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickPlaceFeedback>) istream)
  "Deserializes a message object of type '<PickPlaceFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'info) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'info) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickPlaceFeedback>)))
  "Returns string type for a message object of type '<PickPlaceFeedback>"
  "my_services/PickPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickPlaceFeedback)))
  "Returns string type for a message object of type 'PickPlaceFeedback"
  "my_services/PickPlaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickPlaceFeedback>)))
  "Returns md5sum for a message object of type '<PickPlaceFeedback>"
  "c10fc26d5cca9a4b9114f5fc5dea9570")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickPlaceFeedback)))
  "Returns md5sum for a message object of type 'PickPlaceFeedback"
  "c10fc26d5cca9a4b9114f5fc5dea9570")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickPlaceFeedback>)))
  "Returns full string definition for message of type '<PickPlaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string info~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickPlaceFeedback)))
  "Returns full string definition for message of type 'PickPlaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string info~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickPlaceFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'info))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickPlaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PickPlaceFeedback
    (cl:cons ':info (info msg))
))
